# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Excaliown < Formula
  desc ""
  homepage "https://excaliown.matteogassend.com"
  version "0.0.12"

  on_macos do
    url "https://github.com/matfire/excaliown/releases/download/0.0.12/excaliown_Darwin_all.tar.gz"
    sha256 "1b5c3198ed06c7ca9fb9ea0bbf8f7275e0bba5bcfd8e14ec490b6125bedbaf7f"

    def install
      bin.install "excaliown"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/matfire/excaliown/releases/download/0.0.12/excaliown_Linux_x86_64.tar.gz"
        sha256 "3ed6fec58b79f9a812e4479b000f574d66fa2f3128ae09690693bdb6d9a914f6"

        def install
          bin.install "excaliown"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/matfire/excaliown/releases/download/0.0.12/excaliown_Linux_arm64.tar.gz"
        sha256 "f6c5c6e06be78658f4202889d0d975e5e53d8310f4c3c772a1ce01b71a00ae20"

        def install
          bin.install "excaliown"
        end
      end
    end
  end
end
