# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Excaliown < Formula
  desc ""
  homepage "https://excaliown.matteogassend.com"
  version "0.0.13"

  on_macos do
    url "https://github.com/matfire/excaliown/releases/download/0.0.13/excaliown_Darwin_all.tar.gz"
    sha256 "0ed38d6a72738ec6ba29e64821c0afb11a865afe9b257cdb2d2f3ea088f83531"

    def install
      bin.install "excaliown"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/matfire/excaliown/releases/download/0.0.13/excaliown_Linux_x86_64.tar.gz"
        sha256 "62216de996cb2ae137914527b7c1b71c509b9030cd5cbf6914ce8594bbdbcabb"

        def install
          bin.install "excaliown"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/matfire/excaliown/releases/download/0.0.13/excaliown_Linux_arm64.tar.gz"
        sha256 "a4bde3e4af1bccb711bb91e447dac28d57175e2de6710d52d90f463f880b1f84"

        def install
          bin.install "excaliown"
        end
      end
    end
  end
end
