# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Excaliown < Formula
  desc ""
  homepage "https://excaliown.matteogassend.com"
  version "0.0.1"

  on_macos do
    url "https://github.com/matfire/excaliown/releases/download/0.0.1/excaliown_Darwin_all.tar.gz"
    sha256 "59c96a8ce4a9d33a5d27597165032a3c5e563eb216fba0eb393883aea74a25db"

    def install
      bin.install "excaliown"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/matfire/excaliown/releases/download/0.0.1/excaliown_Linux_x86_64.tar.gz"
        sha256 "599c2b986724211264737a8a5107fd9b9167e2aaa38df4a14bf96de1d25f8d1f"

        def install
          bin.install "excaliown"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/matfire/excaliown/releases/download/0.0.1/excaliown_Linux_arm64.tar.gz"
        sha256 "b1c6fbf0352af1583b6414beffb39510fef2dd6444cf26eaffd9fb65f212db20"

        def install
          bin.install "excaliown"
        end
      end
    end
  end
end
