# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hammer < Formula
  desc ""
  homepage "https://hammer.matteogassend.com"
  version "0.0.53"

  on_macos do
    url "https://github.com/matfire/hammer/releases/download/0.0.53/hammer_Darwin_all.tar.gz"
    sha256 "bf4b9b8d36e0127355fce3bfadf350dc5ad3526a2e58fd6481d0bf311684c720"

    def install
      bin.install "hammer"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/matfire/hammer/releases/download/0.0.53/hammer_Linux_x86_64.tar.gz"
        sha256 "73b3ac63d862559286c6c4d7c7d0e5c99d51b6f3e3a972ec2daa8cb3e731e166"

        def install
          bin.install "hammer"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/matfire/hammer/releases/download/0.0.53/hammer_Linux_arm64.tar.gz"
        sha256 "18eaa884597ad8d17de32cc6045b5a25380f38a2c4ed07542652479f52f13cfb"

        def install
          bin.install "hammer"
        end
      end
    end
  end
end
