# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hammer < Formula
  desc ""
  homepage "https://hammer.matteogassend.com"
  version "0.0.6"

  on_macos do
    url "https://github.com/matfire/hammer/releases/download/0.0.6/hammer_Darwin_all.tar.gz"
    sha256 "2e164c0c6dfe60a33c8e2dee88c3e27468b4e08a418295e2aaa4fb99fcde4b81"

    def install
      bin.install "hammer"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/matfire/hammer/releases/download/0.0.6/hammer_Linux_x86_64.tar.gz"
        sha256 "64eb4704ea93b1e0f7e840f52063b5327a0c2ec1eb7adf78bab6d3833c137801"

        def install
          bin.install "hammer"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/matfire/hammer/releases/download/0.0.6/hammer_Linux_arm64.tar.gz"
        sha256 "310f22e4b5cf71dc95e0009dd1e2749b410cd21b43b6aaea2654493fe133ad7e"

        def install
          bin.install "hammer"
        end
      end
    end
  end
end
