# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Libsqltui < Formula
  desc ""
  homepage "https://libsqltui.matteogassend.com"
  version "0.0.3"

  on_macos do
    url "https://github.com/matfire/libsqltui/releases/download/0.0.3/libsqltui_Darwin_all.tar.gz"
    sha256 "fb38ba2005e534ed6945d1d86fcd4b3b417d16afdb69a912ffc589b12a335461"

    def install
      bin.install "libsqltui"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/matfire/libsqltui/releases/download/0.0.3/libsqltui_Linux_x86_64.tar.gz"
        sha256 "896452dad552d18e10ab0be8bfe72186da311e499921a0e8162e6de67dfa25ef"

        def install
          bin.install "libsqltui"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/matfire/libsqltui/releases/download/0.0.3/libsqltui_Linux_arm64.tar.gz"
        sha256 "667f58ac53a353d2f395f4009fe257750b85b1012a0b91873332f5284e507d5b"

        def install
          bin.install "libsqltui"
        end
      end
    end
  end
end
