# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pocketsctl < Formula
  desc ""
  homepage "https://pockets.matteogassend.com"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matfire/pockets/releases/download/0.0.1/pocketsctl_Darwin_x86_64.tar.gz"
      sha256 "87cbf3967aad6303914217ef6b0fb0890f6db1bb18b6bb99b42651b8e564a298"

      def install
        bin.install "pocketsctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matfire/pockets/releases/download/0.0.1/pocketsctl_Darwin_arm64.tar.gz"
      sha256 "c8b354a6fa0fcea6cdf4289b316e2f659a5ee90cb9a4d5b19253c80e917002dd"

      def install
        bin.install "pocketsctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/matfire/pockets/releases/download/0.0.1/pocketsctl_Linux_x86_64.tar.gz"
        sha256 "13566ac5bdffc9390c0af4af140c871ea624fa572ac4776e40ce04e76ae3bb8d"

        def install
          bin.install "pocketsctl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/matfire/pockets/releases/download/0.0.1/pocketsctl_Linux_arm64.tar.gz"
        sha256 "5e9175ae71a89ff30a2856547c190489e935c79a47fdf3453c7e442f5a9ba762"

        def install
          bin.install "pocketsctl"
        end
      end
    end
  end
end
