# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pocketsctl < Formula
  desc ""
  homepage "https://pockets.matteogassend.com"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matfire/pockets/releases/download/0.0.2/pocketsctl_Darwin_x86_64.tar.gz"
      sha256 "10995b559177786fd78b5e4f6270d6ade99ff1bffe045a72811b7688d87b5c14"

      def install
        bin.install "pocketsctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matfire/pockets/releases/download/0.0.2/pocketsctl_Darwin_arm64.tar.gz"
      sha256 "456dd6d1f8a389ac173500e6ef720c6d408fbe54f7b5319ee987ddcde18a6fab"

      def install
        bin.install "pocketsctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/matfire/pockets/releases/download/0.0.2/pocketsctl_Linux_x86_64.tar.gz"
        sha256 "0acac06a9fe206b94ec1b7167b3cbd7e568ce8a38f9021aa5e3ff85dd22af86f"

        def install
          bin.install "pocketsctl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/matfire/pockets/releases/download/0.0.2/pocketsctl_Linux_arm64.tar.gz"
        sha256 "d447a0ac5f05bc5e55bc592f2eab9508c7696c98846688c18996041c24c14327"

        def install
          bin.install "pocketsctl"
        end
      end
    end
  end
end
