# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pockets < Formula
  desc ""
  homepage "https://pockets.matteogassend.com"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matfire/pockets/releases/download/0.0.1/pockets_Darwin_x86_64.tar.gz"
      sha256 "2b01da0c37dbcb3da59bcaf1f6eccc6a82c83204ebf2ab412759e677787c29b4"

      def install
        bin.install "pockets"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matfire/pockets/releases/download/0.0.1/pockets_Darwin_arm64.tar.gz"
      sha256 "1ca32e69df2afcf3f558ca5fcab341cd867bf6bc1b477ed99f12aca7971db337"

      def install
        bin.install "pockets"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/matfire/pockets/releases/download/0.0.1/pockets_Linux_x86_64.tar.gz"
        sha256 "fd3124542e9e75e262e74d321b0c1d55101abd1dd2d78f867df3b6faa5643a33"

        def install
          bin.install "pockets"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/matfire/pockets/releases/download/0.0.1/pockets_Linux_arm64.tar.gz"
        sha256 "88d015a8dc3c19f43bfc13369a218ea19a74994c8eea51299f8247fc3a743045"

        def install
          bin.install "pockets"
        end
      end
    end
  end
end
