# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pockets < Formula
  desc ""
  homepage "https://pockets.matteogassend.com"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matfire/pockets/releases/download/0.0.2/pockets_Darwin_x86_64.tar.gz"
      sha256 "c7026dcf22f9adc9a18be457b04fed97feda472654ddc72d7731f9ce5ad28b24"

      def install
        bin.install "pockets"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matfire/pockets/releases/download/0.0.2/pockets_Darwin_arm64.tar.gz"
      sha256 "27e8368883c879afabaf9abfb1842f3ae26170f8bb2e706d28655b41cdacd060"

      def install
        bin.install "pockets"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/matfire/pockets/releases/download/0.0.2/pockets_Linux_x86_64.tar.gz"
        sha256 "dc7a7bedbd5a4b6e168b6a108e630125af19d1090334b111166995e2e7f37226"

        def install
          bin.install "pockets"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/matfire/pockets/releases/download/0.0.2/pockets_Linux_arm64.tar.gz"
        sha256 "37140aed58d6be8db81dd371594fa56d8e6e3f1153294d93d9b9085a247ea877"

        def install
          bin.install "pockets"
        end
      end
    end
  end
end
